name: imb_health_app
description: Aplicacion de control de medidas.
publish_to: "none"
version: 1.0.0+1

environment:
  # Esta linea es la clave: ajustada para tu Dart 3.2.3
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Versiones compatibles con Flutter 3.16
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.0 # Usamos la v12 que es muy estable para tu versiÃ³n
  equatable: ^2.0.5
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  flutter_animate: ^4.5.2
  flutter_svg: ^2.0.9
  fl_chart: ^0.66.0
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
